US6 SonySWR21Importer, Review
lucasbuschlinger/BachelorPraktikum pull request #12
Opened 2017-12-01 21:12 UTC by lucasbuschlinger

Implemented US #8, ready to be reviewed.

2017-12-02 18:55 UTC, ocastx requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine (drastischen) Fehler
- [x] FindBugs keine (drastischen) Fehler

Looks good so far, just remove the one ToDo that was done by this PR and we should consider removing the HTML files from the repo as they don't have anything to do with the code.

2017-12-02 18:55 UTC, ocastx commented on plugins/de/opendiabetes/vault/plugin/importer/medtronic/MedtronicImporter.java
>          //TODO javadoc for all Patterns
Remove TODO

2017-12-02 22:54 UTC, lucasbuschlinger commented
Removed ToDo with latest commit.
Good idea with removing the reports, where else should we put those?

Otherwise ready for merge, @ocastx ?

2017-12-03 16:39 UTC, ocastx approved these changes

2017-12-03 16:52 UTC, merged

2017-12-03 16:53 UTC, lucasbuschlinger commented
Done, merging into master, closing this and #8