Restructuring
lucasbuschlinger/BachelorPraktikum pull request #142
Opened 2018-03-24 15:06 UTC by Magnusgaertner

2018-03-24 16:19 UTC, lucasbuschlinger requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [ ] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [ ] Dokumentation in Form von JavaDoc vorhanden
- [ ] Keine logischen Fehler
- [ ] Checkstyle keine Fehler
- [x] FindBugs keine Fehler

Validator sollten noch als Subpackage von Importer sein

2018-03-24 16:19 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/ODVExporter/ODVExporter.java
> +            List<Exporter> exporters = manager.getPluginsOfType(Exporter.class);
Der exportiert ja nur in Dateien, von daher würde ich sage getPluginOfType(FileExporter.class)

2018-03-24 16:19 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/ODVExporter/ODVExporter.java
> +                    exporter.exportDataToFile(exportFile,  data);
1x überflüssiges *leer*

2018-03-24 16:19 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +    //private static Path pluginPath = null;
Kann ja dann raus, genau wie das Setzen davon im Constructor

2018-03-24 16:19 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +        protected  void writeToFile(final String filePath, final List<ExportEntry> csvEntries) throws IOException {
Doppeltes *leer*

2018-03-24 16:19 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/slicelayoutcsv/SliceLayoutCSVExporter.java
> +        protected  List<ExportEntry> prepareData(final List<SliceEntry> data) {
Doppeltes *leer*

2018-03-24 16:19 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/importer/medtroniccrawler/MedtronicCrawlerImporter.java
> +        //TODO Dates introduce state to the plugin, is this really necessary?
@ocastx

2018-03-24 16:19 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/exporter/AbstractExporter.java
Empty? Was ist der Nutzen dann?

2018-03-24 16:19 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/exporter/AbstractExporter.java
Bundle-n von AbtractPlugin und ExporterInterface zu einem?

2018-03-24 16:19 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/exporter/FileExporter.java
> +     * @throws IllegalArgumentException Thrown if the given parameter is invalid //TODO is only used by VaultExporter
Muss man halt überlegen, ob die anderen den selben Check + Exception haben sollen oder man es ganz rausnimmt, aber die Diskussion hatten wir ja schon :D

2018-03-24 16:19 UTC, lucasbuschlinger commented on test/de/opendiabetes/tests/plugin/importer/TestImporterUtil.java
Braucht man doch nicht mehr, kann man doch alles super über den Manager machen?

2018-03-24 16:19 UTC, lucasbuschlinger commented on test/de/opendiabetes/tests/plugin/management/ImportAndInterpretDataflowHelper.java
> + *
Doc

2018-03-24 16:19 UTC, lucasbuschlinger commented on test/de/opendiabetes/tests/plugin/management/ImportAndInterpretDataflowHelper.java
> + *
Gesamte Klasse :D

2018-03-24 16:19 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/data/VaultDAO.java
> +import com.j256.ormlite.db.MysqlDatabaseType;
Unused

2018-03-24 16:19 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/exporter/VaultExporter.java
> +            throw new IllegalArgumentException("Data cannot be empty"); //TODO better return null and remove IllegalArgumentException from parent class aswell
\> 140 Zeichen

2018-03-24 16:19 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/importer/Importer.java
>   */
Ebenfalls leer...

2018-03-24 16:36 UTC, Magnusgaertner commented on src/de/opendiabetes/vault/plugin/exporter/AbstractExporter.java
ok wird refactored...

2018-03-24 16:52 UTC, Magnusgaertner commented on src/de/opendiabetes/vault/plugin/importer/Importer.java
>   */
dient als oberinterface von Crawler- und FileImporters

2018-03-24 17:13 UTC, Magnusgaertner commented on plugins/de/opendiabetes/vault/plugin/exporter/ODVExporter/ODVExporter.java
> +            List<Exporter> exporters = manager.getPluginsOfType(Exporter.class);
done

2018-03-24 17:13 UTC, Magnusgaertner commented on plugins/de/opendiabetes/vault/plugin/exporter/ODVExporter/ODVExporter.java
> +                    exporter.exportDataToFile(exportFile,  data);
done

2018-03-24 17:13 UTC, Magnusgaertner commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +    //private static Path pluginPath = null;
done

2018-03-24 17:13 UTC, Magnusgaertner commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +        protected  void writeToFile(final String filePath, final List<ExportEntry> csvEntries) throws IOException {
done

2018-03-24 17:13 UTC, Magnusgaertner commented on plugins/de/opendiabetes/vault/plugin/exporter/slicelayoutcsv/SliceLayoutCSVExporter.java
> +        protected  List<ExportEntry> prepareData(final List<SliceEntry> data) {
done

2018-03-24 17:14 UTC, Magnusgaertner commented on test/de/opendiabetes/tests/plugin/importer/TestImporterUtil.java
done

2018-03-24 17:14 UTC, Magnusgaertner commented on test/de/opendiabetes/tests/plugin/management/ImportAndInterpretDataflowHelper.java
> + *
done

2018-03-24 17:14 UTC, Magnusgaertner commented on src/de/opendiabetes/vault/data/VaultDAO.java
> +import com.j256.ormlite.db.MysqlDatabaseType;
done

2018-03-24 17:14 UTC, Magnusgaertner commented on src/de/opendiabetes/vault/plugin/exporter/VaultExporter.java
> +            throw new IllegalArgumentException("Data cannot be empty"); //TODO better return null and remove IllegalArgumentException from parent class aswell
done

2018-03-24 17:19 UTC, Magnusgaertner commented
es fehlt meiner Meinung nach nurnoch die IllegalArgument vs return null sache

2018-03-24 17:28 UTC, Magnusgaertner commented
ready for review again ;)

2018-03-24 18:51 UTC, lucasbuschlinger requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [ ] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine Fehler
- [x] FindBugs keine Fehler

2018-03-24 18:51 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/sourcecode/SourceCodeExporter.java
> +         * @param data The to be exported.
'data' vergessen

2018-03-24 18:51 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/importer/crawlerimporter/CrawlerImporter.java
> +
Extra linebreak, JavaDoc sollte immer genau dran sein, oder?

2018-03-24 18:51 UTC, lucasbuschlinger commented on test/de/opendiabetes/tests/plugin/importer/TestImporterUtil.java
Also aus dem Projekt entfernen oder noch behalten?

2018-03-24 18:51 UTC, lucasbuschlinger commented on build.xml
> +    <!--target name="prepare_for_tests">
Kann ganz raus

2018-03-25 10:47 UTC, Magnusgaertner commented
und nun? :)

2018-03-25 10:55 UTC, lucasbuschlinger approved these changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine Fehler
- [x] FindBugs keine Fehler

2018-03-25 10:55 UTC, lucasbuschlinger commented
Close, reopen, merge würde ich sagen :D

2018-03-25 10:55 UTC, merged