Squashed all remaining Bugs
lucasbuschlinger/BachelorPraktikum pull request #151
Opened 2018-03-29 07:57 UTC by lucasbuschlinger

Remaining is only the ActivityTypes JavaDoc, but this has been declared as undesired

2018-03-29 09:37 UTC, ghtina requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine (drastischen) Fehler
- [x] FindBugs keine (drastischen) Fehler

Mit dem Switch-Case in MedtronicImporter nochmal AG fragen.

2018-03-29 17:20 UTC, MarkusHenkel commented
Hab mir jetzt nicht alles im Detail ganz genau angeschaut, aber an den meisten Stellen steht UNINITZIALIZED statt UNINITIALIZED, sprich ein Z in der Mitte zu viel.

2018-03-29 19:18 UTC, lucasbuschlinger commented
Whoop, danke @MarkusHenkel

2018-03-29 21:20 UTC, lucasbuschlinger commented
Should now be done, someone please re-review

2018-03-30 06:10 UTC, ghtina approved these changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine (drastischen) Fehler
- [x] FindBugs keine (drastischen) Fehler

Everything is fine.

2018-03-30 06:10 UTC, merged