Feature/us10 Review
lucasbuschlinger/BachelorPraktikum pull request #39
Opened 2018-01-05 16:16 UTC by Magnusgaertner

2018-01-06 12:31 UTC, lucasbuschlinger requested changes
- [x] Werden korrekte Typen benutzt?
- [] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [ ] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine Fehler
- [x] FindBugs keine Fehler


Zu "Methoden haben korrekte Sichtbarkeit": getDelimiter() wird ja nur hier benutzt, da die Delimiter Sache ja für alle CSV Importer hier geregelt wird, also kann getDelimiter entweder private sein oder man verwendet direkt die Variable delimiter

2018-01-06 12:31 UTC, lucasbuschlinger commented on test/de/opendiabetes/tests/plugin/importer/MedtronicImporterTest.java
> +
Es sind zwar nur Tests, jedoch wär es schön, wenn auch hier vollständige Sätze stehen würde, also Start mit einem Großbuchstaben und Ende mit einem Punkt

- testdata which cannot 
- Der 2. Satz ist auch irgendwie grammatikalisch komisch :D Wie wär's mit "It also sometimes happens, that you need to delete the lib folder from the plugin in order to get this working."?

2018-01-06 12:31 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/importer/medtronic/MedtronicImporter.java
> +         * no preprocessing needed.
Großbuchstabe am Satzanfang bitte :)

2018-01-06 12:31 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/importer/CSVImporter.java
> +     * allows to set the delimiter to use.
Allows

2018-01-06 12:31 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/importer/CSVImporter.java
> +                        "please set the delimiter property if the following format: \n"
Please ... property _in_ the following format

2018-01-06 12:31 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/importer/CSVImporter.java
> +     * method used to detect the valid delimiter by trying to validate the header using a given delimiter
Method und Punkt am Ende

2018-01-06 12:31 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/importer/CSVImporter.java
> -        List<String[]> metaEntries = new ArrayList<>();
Warum hast du die metaEntries entfernt?
Ja sie sind aktuell überflüssig, aber Jens hatte doch gesagt, dass die für etwaige spätere Erweiterungen gedacht sind, oder?

2018-01-06 12:31 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/importer/CSVImporter.java
> +            if (getDelimiter() == 0) { //try to detect the delimiter by try n error
trial and error ;)

2018-01-07 11:34 UTC, Magnusgaertner commented on plugins/de/opendiabetes/vault/plugin/importer/CSVImporter.java
> +     * method used to detect the valid delimiter by trying to validate the header using a given delimiter
Meiner Meinung nach ist protected hier die angemessene Sichtbarkeit, auch wenn der getter nur vom CSVImporter genutzt wird

2018-01-07 11:40 UTC, Magnusgaertner commented on plugins/de/opendiabetes/vault/plugin/importer/CSVImporter.java
> -        List<String[]> metaEntries = new ArrayList<>();
Ja und ja, durch das extrahieren "getValidatedCreader" habe ich die metaEntries gelöscht. Ich füge sie wieder hinzu ;)

2018-01-07 11:56 UTC, Magnusgaertner commented
Habe die angemerkten Punkte korrigiert, abgesehen von der Sichtbarkeit von getDelimiter. Meiner Meinung nach ist protected hier die angemessene Sichtbarkeit.

2018-01-07 14:48 UTC, lucasbuschlinger approved these changes

2018-01-07 14:49 UTC, lucasbuschlinger approved these changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine Fehler
- [x] FindBugs keine Fehler

2018-01-07 14:50 UTC, merged

2018-01-07 14:50 UTC, lucasbuschlinger commented
Done, concludes #19