restructured Plugin interface
lucasbuschlinger/BachelorPraktikum pull request #75
Opened 2018-02-10 10:19 UTC by Magnusgaertner

All Plugin Interfaces implement one common OpenDiabetes Plugin interface now --> preventing duplicated code

2018-02-10 17:14 UTC, lucasbuschlinger requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [ ] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [ ] Checkstyle keine (drastischen) Fehler
- [x] FindBugs keine Fehler

2018-02-10 17:14 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/AbstractExporter.java
>  import java.util.ArrayList;
Checkstyle: Unused import, bitte entfernen

2018-02-10 17:14 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/common/AbstractPlugin.java
> +public abstract class AbstractPlugin implements  OpenDiabetesPlugin{
Checkstyle: Leerzeichen vor { fehlt

2018-02-10 17:14 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/common/AbstractPlugin.java
> + *
JavaDoc fehlt

2018-02-10 17:14 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/common/OpenDiabetesPlugin.java
> +     *
JavaDoc fehlt

2018-02-10 17:14 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/common/package-info.java
> + * //TODO javadoc
JavaDoc fehlt

Checkstyle: Newline am Ende der Datei fehlt

2018-02-10 17:14 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/exporter/Exporter.java
>  import java.util.List;
java.util.Properties & java.util.logging.Logger sind unused Imports, bitte entfernen

2018-02-10 17:14 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/importer/Importer.java
>  import java.util.List;
java.util.Properties & java.util.logging.Logger sind unused Imports, bitte entfernen

2018-02-12 20:18 UTC, Magnusgaertner commented
requested changes should be fixed, ready for review again :)

2018-02-12 20:23 UTC, lucasbuschlinger approved these changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine Fehler
- [x] FindBugs keine Fehler

2018-02-12 20:23 UTC, merged

2018-02-12 20:24 UTC, lucasbuschlinger commented
Nice, re-reviewed, approved and merged :)