Feature/us24
lucasbuschlinger/BachelorPraktikum pull request #80
Opened 2018-02-13 14:37 UTC by ocastx

2018-02-13 21:04 UTC, lucasbuschlinger requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [ ] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [ ] Checkstyle keine Fehler
- [x] FindBugs keine (drastischen) Fehler

Die ganzen printlns sollten doch eher über LOG.log loggen oder? Das auf die Konsole printen bringt ja nichts

Und die Sache mit dem Skript

2018-02-13 21:04 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +import java.io.*;
Eine unserer Regeln ist: Keine Sternimporte

2018-02-13 21:04 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +                String s = null;
Vollständige, klare Variablennamen bitte

2018-02-13 21:04 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +                String s = null;
Variablenname...

2018-02-13 21:04 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +                Process process = Runtime.getRuntime().exec(new String[]{"python", "ploty.py", "-f", dataPath, "-o", outputPath});
ploty.py ist plot.py
Und bei mir muss man den pfad von project-root zum Script direkt angeben und das Skript wird nicht mit in die Plugin-ZIP gelegt (genauso wie die config.json)

2018-02-13 21:09 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +                Process process = Runtime.getRuntime().exec(new String[]{"python", "ploty.py", "-f", dataPath, "-o", outputPath});
Pfad zum Skript vielleicht über die Config setzen?

2018-02-13 21:28 UTC, lucasbuschlinger commented on plugins/de/opendiabetes/vault/plugin/exporter/plotterexporter/PlotterExporter.java
> +                Process process = Runtime.getRuntime().exec(new String[]{"python", "ploty.py", "-f", dataPath, "-o", outputPath});
Am besten mit Java Standardfunktionalität resolven lassen

2018-02-13 21:39 UTC, ocastx commented
Sollte jetzt alles behoben sein, please re-review

2018-02-14 15:33 UTC, lucasbuschlinger approved these changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine (drastischen) Fehler
- [x] FindBugs keine (drastischen) Fehler

2018-02-14 15:35 UTC, merged