Reworked exporters to them not having DB access
lucasbuschlinger/BachelorPraktikum pull request #82
Opened 2018-02-13 17:38 UTC by lucasbuschlinger

All tested with data and stuff

2018-02-13 18:16 UTC, lucasbuschlinger commented
Äh, mir fällt gerade beim Testen vom ODV auf, dass jetzt das mit den Optionen und der periodRestriction logischerweise nicht mehr funktioniert, ich mach das mal noch

2018-02-14 10:11 UTC, ocastx commented
- [ ] Werden korrekte Typen benutzt?
- [ ] Methoden haben korrekte Sichtbarkeit
- [ ] Variablen haben korrekte Sichtbarkeit
- [ ] Keine Rechtschreibfehler (Schrift/Grammatik)
- [ ] Code gut verständlich
- [ ] Eindeutige Variablennamen
- [ ] Dokumentation in Form von JavaDoc vorhanden
- [ ] Keine logischen Fehler
- [ ] Checkstyle keine (drastischen) Fehler
- [ ] FindBugs keine (drastischen) Fehler

2018-02-14 10:13 UTC, ocastx commented
Nur ein CheckStyle Fix im noch im VaultExporter der aber vorher schon drin war, ansonsten i. O. 👍

2018-02-14 10:14 UTC, ocastx requested changes

2018-02-14 10:14 UTC, ocastx commented on plugins/de/opendiabetes/vault/plugin/exporter/FileExporter.java
> +        List<VaultEntry> tempData = new ArrayList<>();
Die Einrückung von dem Funktionsinhalt ist hier weird

2018-02-14 15:03 UTC, lucasbuschlinger commented
Einrückung gefixed
Ja der Checkstyle Error existiert in der gleich Form auch in anderen Klassen, müssen wir mal mit Jens drüber sprechen

2018-02-14 15:04 UTC, merged

2018-02-14 15:06 UTC, lucasbuschlinger commented
Kein re-review, @ocastx ? :D

2018-02-14 15:31 UTC, ocastx commented
Ups, doch aber github hat anscheinend die liste nicht gepostet :D 

- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine (drastischen) Fehler
- [x] FindBugs keine (drastischen) Fehler