Plugin management
lucasbuschlinger/BachelorPraktikum pull request #84
Opened 2018-02-13 18:17 UTC by Magnusgaertner

solves #76

2018-02-13 23:12 UTC, lucasbuschlinger requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [ ] Eindeutige Variablennamen
- [ ] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine (drastischen) Fehler
- [x] FindBugs keine (drastischen) Fehler

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * internal plugin manager provided by pf4j.
Für die Konsistenz sollte der Satz mit Großbuchstaben anfangen

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * map holding all loaded plugins.
Für die Konsistenz sollte der Satz mit Großbuchstaben anfangen

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +                    .filter(y -> pf4jManager.getExtensions(y).size() != 0) //list only compatible plugins that are available
Auch im Lambda vollständige Variablennamen

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +    /**
JavaDoc: Beschreibung

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +    /**
JavaDoc: Beschreibung

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * @param plugin the plugin that is compatible with all the plugins returned
JavaDoc: Beschreibung

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * @param plugins a list of Plugins
JavaDoc: Beschreibung

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * @param pluginIDs a list of plugin IDs
JavaDoc: Beschreibung

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * @param type     the class of the plugin
JavaDoc: Beschreibung

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +        //return plugin.getClass().getProtectionDomain().getCodeSource().getLocation().getPath();
Kommentar kann raus?

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +            //Assert.fail("path to configuration not found");
Kommentar kann auch raus?

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/common/OpenDiabetesPlugin.java
> +     * @return a list of plugin names that are known to be compatible with this plugin
JavaDoc: Beschreibung

2018-02-13 23:12 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * Make sure that load config was called on the plugins before,
Ware gut, wenn man hier auf loadConfig verlinkt

2018-02-14 19:02 UTC, Magnusgaertner commented
ready to re-review ;) @lucasbuschlinger

2018-02-14 19:15 UTC, lucasbuschlinger requested changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [ ] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [ ] Checkstyle keine Fehler
- [x] FindBugs keine Fehler

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/common/AbstractPlugin.java
> +     * and returns the list mapped by the key "compatiblePlugins"
Checkstyle: Satz sollte mit einem Punkt enden

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/common/OpenDiabetesPlugin.java
> +     * for an implementation.
Checkstyle: Der Satz sollte mit einem Punkt enden

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * by typing getPluginsOfType(Importer.class)
Checkstyle: Der Satz sollte mit einem Punkt enden

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +    /**
JavaDoc: Beschreibung

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +    public List<String> getPluginIDsOfType(final Class type){
Checkstyle: Leerzeichen vor { fehlt:

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +        {
Checkstyle: { sollte in der vorherigen Zeile stehen

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +            if (type.isInstance(plugin)){ result.add(id); }
Checkstyle: Leerzeichen vor { und danach ein Zeilenumbruch ( + dann auch Zeilenumbruch vor } )

2018-02-14 19:15 UTC, lucasbuschlinger commented on src/de/opendiabetes/vault/plugin/management/OpenDiabetesPluginManager.java
> +     * Takes a list of plugin IDs and returns a list of corresponding plugins.S
Ein S zu viel am Ende

2018-02-14 19:31 UTC, Magnusgaertner commented
Alle guten Dinge sind 3...

2018-02-14 19:33 UTC, lucasbuschlinger approved these changes
- [x] Werden korrekte Typen benutzt?
- [x] Methoden haben korrekte Sichtbarkeit
- [x] Variablen haben korrekte Sichtbarkeit
- [x] Keine Rechtschreibfehler (Schrift/Grammatik)
- [x] Code gut verständlich
- [x] Eindeutige Variablennamen
- [x] Dokumentation in Form von JavaDoc vorhanden
- [x] Keine logischen Fehler
- [x] Checkstyle keine Fehler
- [x] FindBugs keine Fehler

2018-02-14 19:34 UTC, merged